commit all files because Jenkins looks for them: "C:\Users\SC\.jenkins\workspace\Test project\JenkinsWithDotNet.sln" (default target) (1) -> "C:\Users\SC\.jenkins\workspace\Test project\JenkinsWithDotNet\JenkinsWithDotNet.csproj" (default target) (2) -> (CoreCompile target) ->   CSC : error CS2001: Source file 'Properties\AssemblyInfo.cs' could not be found [C:\Users\SC\.jenkins\workspace\Test project\JenkinsWithDotNet\JenkinsWithDotNet.csproj]